Repository jupytercad/JupyterCAD, pull requests merged in 2023-12, with the labels that each got.

#231 Fix missing dev installation
  .pre-commit-config.yaml
  python/jupytercad_lab/package.json
  yarn.lock
Labels: maintenance

#233 Galata bot: Missing hub command
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#232 STEP files support
  .gitignore
  examples/3M_CONNECTOR.STEP
  packages/occ-worker/src/actions.ts
  packages/occ-worker/src/occapi.ts
  packages/occ-worker/src/operatorcache.ts
  packages/opencascade/build.yml
  packages/schema/src/model.ts
  packages/schema/src/schema/any.json
  pyproject.toml
  python/jupytercad_app/src/app/plugins/browser/index.ts
  python/jupytercad_app/webpack.config.js
  python/jupytercad_core/jupytercad_core/step_ydoc.py
  python/jupytercad_core/pyproject.toml
  python/jupytercad_core/src/index.ts
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_core/src/stepplugin/modelfactory.ts
  python/jupytercad_core/src/stepplugin/plugins.ts
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/Render-3M-CONNECTOR-STEP-linux.png
Labels: enhancement

#235 Non-editable step file
  packages/base/src/commands.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
Labels: enhancement

#242 Fix object selection
  packages/base/src/panelview/objectproperties.tsx
  python/jupytercad_app/jupytercad_app/utils.py
  ui-tests/package.json
  ui-tests/playwright.config.js
Labels: bug
