Repository jupytercad/JupyterCAD, pull requests merged in 2023-11, with the labels that each got.

#219 Update links to repository
  docs/source/conf.py
  package.json
  packages/jupytercad-app/package.json
  packages/jupytercad-app/src/app/plugins/mainmenu/menuWidget.ts
  packages/jupytercad-extension/package.json
  packages/jupytercad-opencascade/package.json
Labels: maintenance

#213 Support pydantic 2
  .pre-commit-config.yaml
  jupytercad/notebook/cad_document.py
  package.json
  packages/jupytercad-extension/package.json
  packages/jupytercad-extension/src/sketcher/elements/point.ts
  packages/jupytercad-extension/src/sketcher/panzoom.ts
  packages/jupytercad-extension/style/base.css
  pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#222 Pin pydantic (again)
  .github/workflows/build.yml
  pyproject.toml
Labels: bug

#225 Organization rename
  docs/source/conf.py
  package.json
  packages/base/package.json
  packages/occ-worker/package.json
  packages/opencascade/package.json
  packages/schema/package.json
  python/jupytercad-app/package.json
  python/jupytercad-app/src/app/plugins/mainmenu/menuWidget.ts
  python/jupytercad-core/package.json
  python/jupytercad-lab/package.json
Labels: enhancement

#221 Update OCC build
  packages/occ-worker/package.json
  packages/occ-worker/src/actions.ts
  packages/occ-worker/src/occapi.ts
  packages/occ-worker/src/occparser.ts
  packages/occ-worker/src/operatorcache.ts
  packages/occ-worker/src/types.ts
  packages/occ-worker/src/worker.ts
  packages/occ-worker/worker.webpack.config.js
  packages/opencascade/.gitignore
  packages/opencascade/build_opencascade_wasm.js
  packages/opencascade/package.json
  packages/opencascade/src/index.ts
  packages/opencascade/tsconfig.json
  python/jupytercad-core/extension.webpack.config.js
  yarn.lock
Labels: enhancement

#227 Update release script
  .github/workflows/publish-release.yml
Labels: maintenance
