Repository jupytercad/JupyterCAD, pull requests merged in 2023-03, with the labels that each got.

#113 Pin JupyterLab
  .github/workflows/build.yml
  pyproject.toml
Labels: maintenance

#112 Update README
  CONTRIBUTING.md
  README.md
Labels: documentation

#114 Prepare for release
  .github/workflows/check-release.yml
  package.json
  pyproject.toml
  scripts/bump-version.py
Labels: maintenance

#115 Pin JupyterLab
  pyproject.toml
Labels: maintenance

#116 Remove `pip install -e .` step in the check release workflow
  .github/workflows/check-release.yml
  pyproject.toml
Labels: maintenance

#117 Hide source objects after executing operators
  src/mainview.tsx
  src/worker/occapi.ts
  src/worker/occparser.ts
  ui-tests/tests/tree.spec.ts-snapshots/Tree-Display-example1-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-common-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-cut-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example1-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example3-FCStd-linux.png
Labels: enhancement

#102 Expose JupyterCad 3d view and APIs in notebook
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/update_galata_references.yaml
  .gitignore
  binder/environment.yml
  examples/cut.FCStd
  jupytercad/__init__.py
  jupytercad/fcstd_ydoc.py
  jupytercad/freecad/loader.py
  jupytercad/freecad/props/__init__.py
  jupytercad/freecad/props/base_prop.py
  jupytercad/freecad/props/property_geometrylist.py
  jupytercad/freecad/props/property_map.py
  jupytercad/freecad/props/property_partshape.py
  jupytercad/freecad/props/property_placement.py
  jupytercad/jcad_ydoc.py
  jupytercad/notebook/__init__.py
  jupytercad/notebook/cad_document.py
  jupytercad/notebook/objects/__init__.py
  jupytercad/notebook/utils.py
  jupytercad/notebook/y_connector.py
  package.json
  pyproject.toml
  src/factory.ts
  src/fcplugin/modelfactory.ts
  src/index.ts
  src/jcadplugin/modelfactory.ts
  src/mainview.tsx
  src/model.ts
  src/notebookrenderer/index.ts
  src/notebookrenderer/model.ts
  src/notebookrenderer/token.ts
  src/notebookrenderer/view.ts
  src/notebookrenderer/widgetManager.ts
  src/notebookrenderer/yCommProvider.ts
  src/toolbar/model.ts
  src/toolbar/parttoolbar.tsx
  src/toolbar/toolbar.tsx
  src/toolbar/widget.tsx
  src/types.ts
  src/widget.tsx
  src/worker/actions.ts
  src/worker/worker.ts
  style/base.css
  yarn.lock
Labels: enhancement
