Repository jupytercad/JupyterCAD, pull requests merged in 2023-01, with the labels that each got.

#83 Do not reset the grid and axe when the scene is empty
  .github/workflows/build.yml
  extension.webpack.config.js
  jupytercad/jcad_ydoc.py
  package.json
  src/fcplugin/modelfactory.ts
  src/jcadplugin/modelfactory.ts
  src/jcadplugin/plugins.ts
  src/mainview.tsx
  src/model.ts
  src/panelview/annotations.tsx
  src/types.ts
  ui-tests/tests/tree.spec.ts
  ui-tests/tests/ui.spec.ts
  yarn.lock
Labels: bug

#97 Fix ci
  .github/workflows/build.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#87 Fix binder
  binder/environment.yml
  binder/jupyter_config.json
  binder/postBuild
  binder/start
  setup.py
Labels: maintenance

#91 FCstd color support
  examples/ArchDetail.FCStd
  jupytercad/fcstd_ydoc.py
  jupytercad/freecad/loader.py
  src/annotation/model.ts
  src/mainview.tsx
  src/model.ts
  src/panelview/annotations.tsx
  src/panelview/model.ts
  src/panelview/objectproperties.tsx
  src/panelview/objecttree.tsx
  src/schema/jcad.json
  src/types.ts
  src/widget.tsx
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Add-example2-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-example4-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-common-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-cut-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example2-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example4-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example5-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example6-FCStd-linux.png
Labels: enhancement

#90 Uses hatch and update releaser
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  MANIFEST.in
  binder/environment.yml
  binder/jupyter_config.json
  jupytercad/__init__.py
  jupytercad/_version.py
  jupytercad/jcad_ydoc.py
  package.json
  pyproject.toml
  setup.cfg
  setup.py
  yarn.lock
Labels: maintenance

#103 Fixes selections
  .gitignore
  src/mainview.tsx
  src/panelview/objecttree.tsx
  ui-tests/tests/ui.spec.ts
Labels: bug

#104 Improve performance
  src/panelview/objecttree.tsx
Labels: enhancement

#106 Fix bot for updating galata references
  .github/workflows/update_galata_references.yaml
Labels: bug

#105 Only compute the bounding box of the visible objects for the reflength
  src/mainview.tsx
  ui-tests/tests/ui.spec.ts-snapshots/Render-example-2D-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example6-FCStd-linux.png
Labels: enhancement

#98 Add extrusion
  jupytercad-opencascade/build.yml
  jupytercad-opencascade/package.json
  jupytercad/freecad/props/__init__.py
  jupytercad/freecad/props/property_distance.py
  package.json
  src/schema/extrusion.json
  src/schema/jcad.json
  src/toolbar/operatortoolbar.tsx
  src/worker/occapi.ts
  src/worker/occparser.ts
  src/worker/types.ts
  yarn.lock
Labels: enhancement

#107 Cleanup selection logic and throttle some events
  pyproject.toml
  src/mainview.tsx
  src/panelview/objecttree.tsx
  src/tools.ts
Labels: bug

#109 Exploded view
  jupytercad-screenshot.png
  src/annotation/model.ts
  src/mainview.tsx
  src/model.ts
  src/toolbar/helpertoolbar.tsx
  src/types.ts
  src/widget.tsx
Labels: enhancement
