Repository jupytercad/JupyterCAD, pull requests merged in 2023-05, with the labels that each got.

#135 Lab app
  .eslintignore
  .github/workflows/build.yml
  .gitignore
  CONTRIBUTING.md
  etc/jupyter/jupyter_server_config.d/jupytercad.json
  jupytercad/__init__.py
  jupytercad/cadapp/__init__.py
  jupytercad/cadapp/cadapp.py
  jupytercad/cadapp/templates/index.html
  jupytercad/cadapp/utils.py
  package.json
  packages/jupytercad-app/package.json
  packages/jupytercad-app/src/app/app.ts
  packages/jupytercad-app/src/app/plugins/browser/index.ts
  packages/jupytercad-app/src/app/plugins/mainmenu/index.ts
  packages/jupytercad-app/src/app/plugins/mainmenu/widget.tsx
  packages/jupytercad-app/src/app/plugins/paths/index.ts
  packages/jupytercad-app/src/app/shell.ts
  packages/jupytercad-app/src/bootstrap.ts
  packages/jupytercad-app/src/main.ts
  packages/jupytercad-app/style/base.css
  packages/jupytercad-app/style/index.css
  packages/jupytercad-app/style/index.js
  packages/jupytercad-app/tsconfig.json
  packages/jupytercad-app/webpack.config.js
  packages/jupytercad-extension/package.json
  packages/jupytercad-extension/src/index.ts
  packages/jupytercad-extension/src/tools.ts
  pyproject.toml
  tsconfig.eslint.json
  tsconfigbase.json
  yarn.lock
Labels: enhancement

#129 Toolbar refactor and styling
  packages/jupytercad-app/style/base.css
  packages/jupytercad-extension/src/commands.ts
  packages/jupytercad-extension/src/factory.ts
  packages/jupytercad-extension/src/formdialog.tsx
  packages/jupytercad-extension/src/index.ts
  packages/jupytercad-extension/src/model.ts
  packages/jupytercad-extension/src/sketcher/sketcherdialog.tsx
  packages/jupytercad-extension/src/toolbar/helpertoolbar.tsx
  packages/jupytercad-extension/src/toolbar/model.ts
  packages/jupytercad-extension/src/toolbar/operatortoolbar.tsx
  packages/jupytercad-extension/src/toolbar/parttoolbar.tsx
  packages/jupytercad-extension/src/toolbar/sketchertoolbar.tsx
  packages/jupytercad-extension/src/toolbar/toolbar.tsx
  packages/jupytercad-extension/src/toolbar/usertoolbaritem.tsx
  packages/jupytercad-extension/src/toolbar/widget.tsx
  packages/jupytercad-extension/src/tools.ts
  packages/jupytercad-extension/src/types.ts
  packages/jupytercad-extension/style/base.css
  packages/jupytercad-extension/style/icon/axes.svg
  packages/jupytercad-extension/style/icon/box.svg
  packages/jupytercad-extension/style/icon/cone.svg
  packages/jupytercad-extension/style/icon/cut.svg
  packages/jupytercad-extension/style/icon/cylinder.svg
  packages/jupytercad-extension/style/icon/extrusion.svg
  packages/jupytercad-extension/style/icon/intersection.svg
  packages/jupytercad-extension/style/icon/sphere.svg
  packages/jupytercad-extension/style/icon/torus.svg
  packages/jupytercad-extension/style/icon/union.svg
  ui-tests/tests/sketcher.spec.ts
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Add-example2-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-example4-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-common-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-cut-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example-2D-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example1-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example2-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example4-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example5-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example6-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jcad-linux.png
Labels: enhancement

#141 Default shape/operator names
  packages/jupytercad-extension/src/commands.ts
Labels: enhancement, UX improvement

#143 Update annotations position on resize
  packages/jupytercad-extension/src/mainview.tsx
Labels: bug, enhancement

#146 Simplify annotations update
  packages/jupytercad-extension/src/mainview.tsx
Labels: enhancement

#140 Add top menu and launcher
  README.md
  jupytercad/cadapp/utils.py
  packages/jupytercad-app/package.json
  packages/jupytercad-app/src/app/plugins/browser/index.ts
  packages/jupytercad-app/src/app/plugins/launcher/index.ts
  packages/jupytercad-app/src/app/plugins/mainmenu/index.ts
  packages/jupytercad-app/src/app/plugins/mainmenu/menuWidget.ts
  packages/jupytercad-app/src/app/plugins/mainmenu/titleWidget.tsx
  packages/jupytercad-app/src/app/plugins/mainmenu/userWidget.tsx
  packages/jupytercad-app/src/main.ts
  packages/jupytercad-app/src/sharedscope.ts
  packages/jupytercad-app/style/base.css
  packages/jupytercad-extension/package.json
  packages/jupytercad-extension/src/commands.ts
  packages/jupytercad-extension/src/jcadplugin/plugins.ts
  packages/jupytercad-extension/src/notebookrenderer/index.ts
  packages/jupytercad-extension/style/icon/axes.svg
  ui-tests/tests/sketcher.spec.ts
  ui-tests/tests/tree.spec.ts
  ui-tests/tests/ui.spec.ts
  yarn.lock
Labels: enhancement

#150 Remove gradient background
  packages/jupytercad-app/style/base.css
  packages/jupytercad-extension/src/mainview.tsx
  packages/jupytercad-extension/src/tools.ts
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Add-example2-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-example4-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-common-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-cut-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example-2D-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example1-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example2-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example4-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example5-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example6-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jcad-linux.png
Labels: enhancement

#145 Multi selection
  packages/jupytercad-extension/src/commands.ts
  packages/jupytercad-extension/src/mainview.tsx
  packages/jupytercad-extension/src/model.ts
  packages/jupytercad-extension/src/panelview/objecttree.tsx
  packages/jupytercad-extension/src/types.ts
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-example3-FCStd-linux.png
Labels: enhancement, UX improvement

#155 Fix: prevent selecting invisible mesh
  packages/jupytercad-extension/src/mainview.tsx
Labels: bug

#156 Update screenshot
  jupytercad-screenshot.png
Labels: documentation

#158 Improve lighting
  packages/jupytercad-extension/src/mainview.tsx
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-example3-FCStd-linux.png
Labels: enhancement

#159 Remove shadowmapping
  packages/jupytercad-extension/src/mainview.tsx
Labels: enhancement

#160 Fix Notebook API view
  packages/jupytercad-extension/src/notebookrenderer/yCommProvider.ts
Labels: bug

#161 Fixup visibility checking
  packages/jupytercad-extension/src/commands.ts
  packages/jupytercad-extension/src/mainview.tsx
  packages/jupytercad-extension/src/panelview/objecttree.tsx
  ui-tests/tests/ui.spec.ts-snapshots/Render-cut-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-example1-FCStd-linux.png
Labels: bug

#164 Improve cache mechanism
  packages/jupytercad-extension/src/worker/occapi.ts
  packages/jupytercad-extension/src/worker/operatorcache.ts
Labels: enhancement

#166 Update jupyter_collaboration dependency
  pyproject.toml
Labels: maintenance

#167 Install python-occ core on galata bot
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#168 Add backend installation check
  jupytercad/cadapp/cadapp.py
  jupytercad/freecad/loader.py
  jupytercad/notebook/cad_document.py
  packages/jupytercad-extension/src/factory.ts
  packages/jupytercad-extension/src/fcplugin/modelfactory.ts
  packages/jupytercad-extension/src/fcplugin/plugins.ts
  packages/jupytercad-extension/src/tools.ts
Labels: enhancement
