Repository jupytercad/JupyterCAD, pull requests merged in 2023-06, with the labels that each got.

#173 NPM Package version fix
  packages/jupytercad-app/package.json
  packages/jupytercad-extension/package.json
  packages/jupytercad-opencascade/package.json
Labels: bug

#177 Add docstrings
  jupytercad/notebook/cad_document.py
Labels: documentation

#176 Fix file paths in Notebook.ipynb
  examples/Notebook.ipynb
Labels: maintenance

#178 Simplify bump version script
  package.json
  pyproject.toml
  scripts/bump-version.py
Labels: maintenance

#172 Add releaser action and pre-commit config
  .eslintignore
  .eslintrc.js
  .github/workflows/check-release.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/update_galata_references.yaml
  .pre-commit-config.yaml
  .prettierignore
  .prettierrc
  .yarnrc.yml
  binder/start
  examples/test.jcad
  jupytercad/__init__.py
  jupytercad/cadapp/__init__.py
  jupytercad/cadapp/cadapp.py
  jupytercad/fcstd_ydoc.py
  jupytercad/freecad/loader.py
  jupytercad/freecad/props/__init__.py
  jupytercad/freecad/props/geometry/geom_circle.py
  jupytercad/freecad/props/geometry/geom_linesegment.py
  jupytercad/freecad/props/property_angle.py
  jupytercad/freecad/props/property_bool.py
  jupytercad/freecad/props/property_distance.py
  jupytercad/freecad/props/property_geometrylist.py
  jupytercad/freecad/props/property_length.py
  jupytercad/freecad/props/property_link.py
  jupytercad/freecad/props/property_link_list.py
  jupytercad/freecad/props/property_map.py
  jupytercad/freecad/props/property_partshape.py
  jupytercad/freecad/props/property_placement.py
  jupytercad/jcad_ydoc.py
  jupytercad/notebook/__init__.py
  jupytercad/notebook/cad_document.py
  jupytercad/notebook/objects/__init__.py
  jupytercad/notebook/utils.py
  jupytercad/notebook/y_connector.py
  packages/jupytercad-extension/style/icon/jvcontrol.svg
  packages/jupytercad-extension/style/icon/minimize.svg
  packages/jupytercad-extension/style/icon/visibility.svg
  packages/jupytercad-extension/style/icon/visibilityOff.svg
  packages/jupytercad-opencascade/build.yml
  pyproject.toml
  setup.py
  ui-tests/jupyter_server_test_config.py
Labels: maintenance

#181 Fix missing static files in cad app
  pyproject.toml
Labels: bug

#182 Update shared scope
  packages/jupytercad-app/package.json
  packages/jupytercad-app/src/sharedscope.ts
  packages/jupytercad-extension/package.json
  yarn.lock
Labels: bug

#184 Missing dependencies
  pyproject.toml
Labels: bug

#187 Hide FreeCAD import message
  jupytercad/freecad/loader.py
  jupytercad/freecad/props/geometry/geom_circle.py
  jupytercad/freecad/props/geometry/geom_linesegment.py
  jupytercad/freecad/props/property_placement.py
  jupytercad/freecad/tools.py
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
Labels: bug

#190 Add docs link in the README
  README.md
Labels: documentation

#193 Compute shape properties
  jupytercad/notebook/cad_document.py
  jupytercad/notebook/objects/__init__.py
  packages/jupytercad-extension/src/mainview.tsx
  packages/jupytercad-extension/src/model.ts
  packages/jupytercad-extension/src/schema/any.json
  packages/jupytercad-extension/src/schema/jcad.json
  packages/jupytercad-extension/src/types.ts
  packages/jupytercad-extension/src/worker/actions.ts
  packages/jupytercad-extension/src/worker/occapi.ts
  packages/jupytercad-extension/src/worker/occparser.ts
  packages/jupytercad-extension/src/worker/operatorcache.ts
  packages/jupytercad-extension/src/worker/types.ts
  packages/jupytercad-opencascade/build.yml
Labels: enhancement

#197 Fix fuse and intersection operator
  packages/jupytercad-extension/src/worker/occapi.ts
Labels: bug

#198 Add annotation and color API
  examples/Notebook.ipynb
  jupytercad/fcstd_ydoc.py
  jupytercad/jcad_ydoc.py
  jupytercad/notebook/cad_document.py
  packages/jupytercad-extension/src/mainview.tsx
  yarn.lock
Labels: enhancement

#202 Add conda instructions
  README.md
Labels: documentation

#205 Fix check release
  lerna.json
Labels: maintenance

#204 Allow changing camera settings
  packages/jupytercad-app/src/app/plugins/mainmenu/menuWidget.ts
  packages/jupytercad-extension/src/commands.ts
  packages/jupytercad-extension/src/mainview.tsx
  packages/jupytercad-extension/src/toolbar/widget.tsx
  packages/jupytercad-extension/src/types.ts
  packages/jupytercad-extension/src/widget.tsx
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-example3-FCStd-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-example3-FCStd-linux.png
Labels: enhancement
