Repository jupytercad/JupyterCAD, pull requests merged in 2024-09, with the labels that each got.

#398 Fix bot behaviour to update snapshots
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#390 Enable Toggling Wireframe View
  packages/base/src/3dview/mainview.tsx
  packages/base/src/commands.ts
  packages/base/src/keybindings.json
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/base/src/widget.ts
  packages/base/style/icon/wireframe.svg
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
  yarn.lock
Labels: enhancement

#400 Fix bot to update snapshots
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#401 Try fixing bot to update snapshots
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#397 Add Color Customization for JupyterCAD Models
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  packages/base/src/commands.ts
  packages/base/src/panelview/formbuilder.tsx
  packages/schema/src/schema/any.json
  packages/schema/src/schema/box.json
  packages/schema/src/schema/chamfer.json
  packages/schema/src/schema/cone.json
  packages/schema/src/schema/cut.json
  packages/schema/src/schema/cylinder.json
  packages/schema/src/schema/extrusion.json
  packages/schema/src/schema/fillet.json
  packages/schema/src/schema/fuse.json
  packages/schema/src/schema/intersection.json
  packages/schema/src/schema/sketch.json
  packages/schema/src/schema/sphere.json
  packages/schema/src/schema/torus.json
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-New-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Undo-linux.png
Labels: enhancement

#402 Fix python console in the standalone app
  package.json
  python/jupytercad_app/jupytercad_app/utils.py
  python/jupytercad_app/package.json
  python/jupytercad_app/src/app/plugins/launcher/index.ts
  python/jupytercad_app/src/main.ts
  python/jupytercad_app/src/sharedscope.ts
  yarn.lock
Labels: bug

#403 Preview PR using appsharing.space
  .github/workflows/binder-on-pr.yml
  .github/workflows/comment-on-pr.yml
Labels: maintenance

#405 Replace toggle wireframe button to the right
  packages/base/src/toolbar/widget.tsx
Labels: bug

#404 Save jupyterlite build artifact
  .github/workflows/build.yml
  .github/workflows/comment-on-pr.yml
Labels: maintenance

#409 Fix jupyterlite deployment
  packages/base/src/toolbar/usertoolbaritem.tsx
Labels: bug

#408 Little darker shade of color for edges
  packages/base/src/3dview/mainview.tsx
Labels: bug

#412 Smart color handling for edges based upon mesh luminance
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#414 Update yjs-widgets dependency + make it shared
  packages/base/package.json
  python/jupytercad_lab/package.json
  python/jupytercad_lab/pyproject.toml
Labels: maintenance

#415 Exclude node_modules from sdists
  python/jupytercad_core/pyproject.toml
  python/jupytercad_lab/pyproject.toml
Labels: maintenance

#416 Try fixing the upload of Github pages
  .github/workflows/build.yml
Labels: maintenance

#417 Remove unneeded jupytercad_lab dependencies
  python/jupytercad_lab/pyproject.toml
Labels: enhancement

#413 Remove the guidata option
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  packages/base/src/commands.ts
  packages/base/src/panelview/objecttree.tsx
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/schema/jcad.json
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
Labels: maintenance, breaking change

#420 Fix dependencies pinning
  python/jupytercad_app/pyproject.toml
  python/jupytercad_lab/pyproject.toml
Labels: maintenance

#421 Remove non-relevant steps
  CONTRIBUTING.md
  docs/source/contributing.rst
Labels: documentation

#422 Fix python api
  examples/Notebook.ipynb
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
Labels: bug

#424 Fix metadata
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
Labels: maintenance

#425 Use SharedModelFactory to create shared model
  python/jupytercad_lab/src/notebookrenderer.ts
Labels: enhancement

#428 Add jcad icon in the launcher
  packages/base/src/tools.ts
  packages/base/style/icon/logo.svg
  python/jupytercad_core/src/jcadplugin/plugins.ts
Labels: enhancement

#430 Add link to playwright report in PR
  .github/workflows/build.yml
  .github/workflows/comment-on-pr.yml
Labels: maintenance

#429 Bump jupyter-collaboration v3
  packages/base/src/toolbar/widget.tsx
  python/jupytercad_app/package.json
  python/jupytercad_core/pyproject.toml
  ui-tests/package.json
  ui-tests/tests/sketcher.spec.ts
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Add-test-jcad-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#364 Include Notebook API into lite kernel deployment
  .github/workflows/build.yml
  lite/environment.yml
  lite/jupyter-lite.json
Labels: enhancement

#433 Lite deployment: Disable docprovider-extension
  lite/jupyter-lite.json
Labels: maintenance

#434 Lite deployment missing deps
  lite/environment.yml
  lite/jupyter-lite.json
Labels: maintenance

#436 Fix lite build
  lite/jupyter-lite.json
Labels: bug

#437 Update example for colors
  examples/test.jcad
Labels: bug

#439 Try fixing galata workflow
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#418 Update `ThreeJS`
  packages/base/package.json
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Add-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jcad-linux.png
  yarn.lock
Labels: maintenance
