Repository jupytercad/JupyterCAD, pull requests merged in 2024-11, with the labels that each got.

#559 Do not update the camera position automatically for single object scene
  packages/base/src/3dview/mainview.tsx
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-test-jcad-linux.png
Labels: bug

#529 Add Translation Controls
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#563 Make selection logic smoother
  packages/base/src/3dview/mainview.tsx
Labels: bug

#564 Fix selection through clip plane
  packages/base/src/3dview/mainview.tsx
Labels: bug

#565 Allow transforming objects when clipping is enabled
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#566 Fix initial selected edges color
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
Labels: bug

#569 Fix selection logic
  packages/base/src/3dview/mainview.tsx
Labels: bug

#570 Introduce IMouseDrag interface
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
Labels: maintenance

#571 Bug fix: Prevent tree from wrongly updating the selection
  packages/base/src/commands.ts
  packages/base/src/panelview/objecttree.tsx
Labels: bug

#577 Add a min-height to the toolbar separator
  python/jupytercad_lab/style/base.css
Labels: bug

#581 Expand undo_manager scope
  python/jupytercad_core/jupytercad_core/jcad_ydoc.py
Labels: bug

#583 Add test for rotated shape
  examples/test.jcad
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
Labels: maintenance

#578 Enable toggling transform controls
  packages/base/src/3dview/mainview.tsx
  packages/base/src/commands.ts
  packages/base/src/toolbar/widget.tsx
  packages/base/src/widget.ts
Labels: enhancement

#584 Add test for exploded view
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/Exploded-test-jcad-linux.png
Labels: maintenance

#587 Show selection in transparency for non-visible objects
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
Labels: UX improvement, enhancement

#591 Add stl and stp icons
  packages/base/src/tools.ts
  packages/base/style/icon/stl.svg
  packages/base/style/icon/stp.svg
  python/jupytercad_core/src/stepplugin/plugins.ts
  python/jupytercad_core/src/stlplugin/plugins.ts
Labels: enhancement

#593 Add transform icon
  packages/base/src/commands.ts
  packages/base/src/tools.ts
  packages/base/style/icon/transform.svg
Labels: enhancement

#594 Disable transform control for readonly files
  packages/base/src/commands.ts
Labels: enhancement

#589 Update UI-tests snapshots
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/sketcher.spec.ts-snapshots/Sketcher-Display-test-jcad-linux.png
  ui-tests/tests/tree.spec.ts-snapshots/Tree-Display-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Exploded-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-New-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Undo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Add-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-3M-CONNECTOR-STEP-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-fan-stl-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jcad-linux.png
Labels: maintenance

#598 Add commands to command palette
  python/jupytercad_core/src/jcadplugin/plugins.ts
Labels: enhancement

#600 Fix missing placement for STL & STEP Files
  python/jupytercad_core/src/stepplugin/model.ts
  python/jupytercad_core/src/stlplugin/model.ts
Labels: bug

#580 Undo opencascade positioning and rotation
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  ui-tests/tests/ui.spec.ts-snapshots/Exploded-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jcad-linux.png
Labels: maintenance

#602 Improve placement info + missing "degrees" info
  packages/schema/src/schema/placement.json
Labels: enhancement

#604 Allow exporting .stl to .jcad
  python/jupytercad_core/jupytercad_core/handlers.py
  python/jupytercad_core/src/stlplugin/model.ts
Labels: bug

#603 Rotation Controls
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#610 Transform controls: undo positioning upon failure
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  packages/base/src/3dview/mainviewmodel.ts
Labels: bug

#614 Fix selection of newly created objects in the 3D view
  packages/base/src/3dview/mainview.tsx
Labels: bug

#615 Do not show the transform if there is no current selection
  packages/base/src/3dview/mainview.tsx
Labels: bug

#616 No transform controls when exploded view is enabled
  packages/base/src/3dview/mainview.tsx
  packages/base/src/3dview/mainviewmodel.ts
  packages/base/src/commands.ts
Labels: bug
