Repository jupytercad/JupyterCAD, pull requests merged in 2024-10, with the labels that each got.

#440 Add viewHelper v2
  packages/base/src/3dview/mainview.tsx
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-New-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Undo-linux.png
Labels: enhancement

#441 Improve the UX of the clip-plane and wireframe buttons
  packages/base/src/commands.ts
Labels: enhancement, UX improvement

#460 Add icons in filebrowser
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_core/src/stepplugin/plugins.ts
  python/jupytercad_core/src/stlplugin/plugins.ts
Labels: enhancement

#461 Rename launcher button
  python/jupytercad_app/src/app/plugins/launcher/index.ts
  python/jupytercad_core/src/jcadplugin/plugins.ts
  ui-tests/tests/ui.spec.ts
Labels: maintenance

#465 Reduce field of view of Camera
  packages/base/src/3dview/mainview.tsx
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-New-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Undo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Add-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-3M-CONNECTOR-STEP-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-fan-stl-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jcad-linux.png
Labels: maintenance

#455 Reactive toolbar w.r.t. width
  packages/base/src/toolbar/widget.tsx
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
Labels: enhancement

#466 Add `logoicon` as tabicon
  python/jupytercad_core/src/jcadplugin/plugins.ts
Labels: enhancement

#452 Button to Center view on visible objects
  packages/base/src/3dview/mainview.tsx
  packages/base/src/panelview/model.ts
  packages/base/src/panelview/objecttree.tsx
  packages/base/src/types.ts
Labels: enhancement

#451 Add all proposed Keyboard shortcuts
  packages/base/src/3dview/mainview.tsx
  packages/base/src/keybindings.json
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/rightpanel.tsx
Labels: enhancement, UX improvement

#448 Sync editor upon editor change
  python/jupytercad_core/src/factory.ts
  python/jupytercad_core/src/plugin.ts
Labels: bug

#470 Remove unnecessary warning
  packages/base/src/panelview/formbuilder.tsx
Labels: maintenance

#469 Fix breaking viewHelper while changing camera
  packages/base/src/3dview/mainview.tsx
Labels: bug

#472 Update jupyter-collaboration v3.0.0-beta.8
  package.json
  packages/base/package.json
  packages/schema/package.json
  packages/schema/src/doc.ts
  python/jupytercad_app/package.json
  python/jupytercad_core/package.json
  python/jupytercad_core/pyproject.toml
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_core/src/stepplugin/plugins.ts
  python/jupytercad_core/src/stlplugin/plugins.ts
  python/jupytercad_lab/package.json
  python/jupytercad_lab/src/notebookrenderer.ts
  yarn.lock
Labels: maintenance

#474 Add clipping plane and exploded view icons
  packages/base/src/tools.ts
  packages/base/style/icon/clipPlane.svg
  packages/base/style/icon/exploded.svg
Labels: enhancement

#473 Bounding Box for Selection
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-New-linux.png
Labels: enhancement

#490 Exaggerate clip plane size
  packages/base/src/3dview/mainview.tsx
Labels: bug

#492 Handle zoom while camera change
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#494 Bump yjs-widgets>=0.3.7
  python/jupytercad_app/package.json
  python/jupytercad_lab/package.json
  python/jupytercad_lab/pyproject.toml
  yarn.lock
Labels: maintenance

#497 Bump pydantic==2.9.2 for build
  requirements-build.txt
Labels: maintenance

#495 Use logarithmic depth buffer
  packages/base/src/3dview/mainview.tsx
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Undo-linux.png
Labels: enhancement

#493 refLength was not always updating
  packages/base/src/3dview/mainview.tsx
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jcad-linux.png
Labels: enhancement

#499 Fix README comment about freecad
  README.md
Labels: documentation

#498 Streamline edge selection
  packages/base/src/3dview/mainview.tsx
Labels: bug

#501 Comparable Default Dimensions
  packages/base/src/commands.ts
Labels: UX improvement, enhancement

#507 Cadapp version
  python/jupytercad_app/jupytercad_app/cadapp.py
Labels: bug

#504 Add `--no-occ-build` option
  CONTRIBUTING.md
  packages/opencascade/build_opencascade_wasm.js
  packages/opencascade/package.json
  scripts/dev-install.py
  yarn.lock
Labels: maintenance

#508 Fix clip plane color
  packages/base/src/3dview/mainview.tsx
Labels: bug

#510 Orthographic camera: fix missing near and far parameters
  packages/base/src/3dview/mainview.tsx
Labels: bug

#506 Smooth animated camera movement to center object
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#513 Fix clip plane color
  packages/base/src/3dview/mainview.tsx
Labels: bug

#514 Fix lighting issue
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
Labels: bug

#515 Fixed intensity & decay
  packages/base/src/3dview/mainview.tsx
Labels: bug

#516 Bump @jupyter/ydoc
  package.json
  packages/base/package.json
  packages/schema/package.json
  python/jupytercad_app/package.json
  python/jupytercad_core/package.json
  python/jupytercad_lab/package.json
  yarn.lock
Labels: maintenance

#519 JupyterCAD icons to left and right tabs
  packages/base/src/tools.ts
  packages/base/style/icon/clipping.svg
  packages/base/style/icon/jvcontrol.svg
  python/jupytercad_lab/src/index.ts
Labels: enhancement

#520 Update main logo
  packages/base/style/icon/logo.svg
Labels: enhancement

#523 Cleanup and fix SVG logo
  packages/base/style/icon/logo.svg
Labels: bug

#522 Reorder toolbar icons
  packages/base/src/toolbar/widget.tsx
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
Labels: enhancement

#521 Fix bounding box on exploded view
  packages/base/src/3dview/mainview.tsx
Labels: bug

#525 Set collaborative attribute to False in Jupyterlite
  packages/schema/src/model.ts
  python/jupytercad_core/src/jcadplugin/modelfactory.ts
  python/jupytercad_core/src/stepplugin/modelfactory.ts
  python/jupytercad_core/src/stlplugin/modelfactory.ts
Labels: bug

#505 Fix handling of theme change
  packages/base/src/3dview/mainview.tsx
  packages/base/src/panelview/objecttree.tsx
  packages/base/src/sketcher/sketcherwidget.tsx
  packages/base/src/tools.ts
Labels: bug

#527 Grey icon in tabs
  packages/base/style/icon/logo.svg
  python/jupytercad_lab/style/base.css
Labels: enhancement

#528 Pin Python in docs build
  docs/environment.yml
  docs/source/conf.py
Labels: documentation, maintenance

#530 Update CAD app to include missing collaboration tokens
  .gitignore
  python/jupytercad_app/jupytercad_app/utils.py
  python/jupytercad_app/package.json
  python/jupytercad_app/src/app/plugins/mainmenu/menuWidget.ts
  python/jupytercad_app/src/main.ts
  python/jupytercad_app/src/sharedscope.ts
  yarn.lock
Labels: bug

#531 Allow opening JupyterCAD documents with the JSON viewer + Allow opening STL and STEP in JupyterLite
  .github/workflows/build.yml
  package.json
  packages/base/package.json
  packages/schema/src/model.ts
  python/jupytercad_app/package.json
  python/jupytercad_app/src/app/app.ts
  python/jupytercad_app/src/main.ts
  python/jupytercad_core/package.json
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_core/src/stepplugin/model.ts
  python/jupytercad_core/src/stepplugin/modelfactory.ts
  python/jupytercad_core/src/stepplugin/plugins.ts
  python/jupytercad_core/src/stlplugin/model.ts
  python/jupytercad_core/src/stlplugin/modelfactory.ts
  python/jupytercad_core/src/stlplugin/plugins.ts
  python/jupytercad_lab/package.json
  ui-tests/tests/sketcher.spec.ts
  ui-tests/tests/tree.spec.ts
  ui-tests/tests/ui.spec.ts
  yarn.lock
Labels: enhancement

#533 Fix context switching for the right panel
  packages/base/src/panelview/objectproperties.tsx
Labels: bug

#534 Set visible back to True for operator inputs upon removal of the output
  packages/base/src/panelview/objecttree.tsx
Labels: enhancement

#536 Revert "Orthographic camera: fix missing near and far parameters"
  packages/base/src/3dview/mainview.tsx
Labels: bug

#538 Fix clip plane controls when switching camera projection
  packages/base/src/3dview/mainview.tsx
Labels: bug

#541 Unpin jupyterlite-xeus in lite build
  .github/workflows/build.yml
Labels: maintenance

#539 ClipPlane: fix z-fighting artifacts
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#542 Improve selection logic
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#540 Object properties panel: Use selected object name as the title
  packages/base/src/commands.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/rightpanel.tsx
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
Labels: enhancement

#548 Fix ui issues
  packages/base/src/3dview/mainview.tsx
  python/jupytercad_lab/style/base.css
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Undo-linux.png
Labels: bug

#549 Prevent getting back to non-wireframe after operator
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
Labels: bug

#552 Re-add `setColor` api
  examples/Notebook.ipynb
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
Labels: bug

#555 Refactor Bounding Box Logic
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
Labels: bug

#554 Swap annotation and object properties panel
  packages/base/src/panelview/formbuilder.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/objecttree.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/suggestion/model.ts
  packages/base/src/suggestion/suggestionpanel.tsx
  packages/base/src/suggestion/view.tsx
  packages/base/src/tools.ts
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_lab/src/index.ts
  ui-tests/tests/sketcher.spec.ts-snapshots/Sketcher-Circle-test-jcad-linux.png
  ui-tests/tests/tree.spec.ts-snapshots/Tree-Display-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-New-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Undo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
Labels: enhancement
