Repository jupytercad/JupyterCAD, pull requests merged in 2024-07, with the labels that each got.

#377 Fix rendering stl and step files
  packages/base/src/3dview/mainview.tsx
  python/jupytercad_core/pyproject.toml
  python/jupytercad_lab/pyproject.toml
Labels: bug

#379 Update Contributing Guide for Development Installation
  CONTRIBUTING.md
Labels: documentation

#380 Pin reacttrs
  python/jupytercad_lab/pyproject.toml
Labels: bug

#383 Fix code format
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#386 #78 Re-enable `jupyterlab.browser_check`
  .github/workflows/build.yml
Labels: maintenance

#389 Position & Axis inputs in a row
  python/jupytercad_lab/style/base.css
Labels: enhancement

#388 Delete Object Keyboard Shortcut
  packages/base/src/commands.ts
  packages/base/src/keybindings.json
  packages/base/src/panelview/objecttree.tsx
  packages/base/tsconfig.json
Labels: enhancement

#385 Improve shape metadata update logic
  packages/base/src/3dview/mainviewmodel.ts
  packages/base/src/commands.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/occ-worker/src/worker.ts
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  python/jupytercad_core/jupytercad_core/jcad_ydoc.py
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-New-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Undo-linux.png
Labels: enhancement
