Repository jupytercad/JupyterCAD, pull requests merged in 2024-04, with the labels that each got.

#341 Refactor 3D view
  packages/base/src/3dview/followindicator.tsx
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/index.ts
  packages/base/src/3dview/mainview.tsx
  packages/base/src/3dview/mainviewmodel.ts
  packages/base/src/3dview/spinner.tsx
  packages/base/src/commands.ts
  packages/base/src/index.ts
  packages/base/src/panelview/objecttree.tsx
  packages/base/src/tools.ts
  packages/base/src/widget.tsx
  yarn.lock
Labels: maintenance

#347 Visual regression tests: Increase cell execution timeout
  ui-tests/tests/notebook.spec.ts
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
Labels: maintenance

#348 Wider edge operators support
  examples/Notebook.ipynb
  python/jupytercad_app/src/app/plugins/mainmenu/menuWidget.ts
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
  python/jupytercad_lab/jupytercad_lab/notebook/objects/__init__.py
Labels: enhancement

#350 Improve post-processing system
  packages/base/package.json
  packages/base/src/3dview/mainview.tsx
  packages/base/src/3dview/mainviewmodel.ts
  packages/occ-worker/src/actions.ts
  packages/occ-worker/src/occapi/postOperator.ts
  packages/occ-worker/src/types.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/schema/jcad.json
  yarn.lock
Labels: enhancement

#351 Add await for postShape before sending
  packages/base/src/3dview/mainview.tsx
  packages/base/src/3dview/mainviewmodel.ts
Labels: bug

#353 Update 3D rendering logic
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  packages/base/src/3dview/mainviewmodel.ts
  packages/occ-worker/src/occapi/makeShapeFromMesh.ts
  packages/occ-worker/src/occapi/stepIO.ts
  packages/occ-worker/src/occparser.ts
  packages/schema/src/interfaces.ts
  python/jupytercad_lab/style/base.css
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  yarn.lock
Labels: bug, enhancement
