Repository jupytercad/JupyterCAD, pull requests merged in 2024-06, with the labels that each got.

#349 Error handling
  packages/base/src/3dview/mainviewmodel.ts
  packages/base/src/commands.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/widget.tsx
  packages/occ-worker/src/occapi/operatorCache.ts
  packages/occ-worker/src/types.ts
  packages/occ-worker/src/worker.ts
  packages/schema/src/interfaces.ts
  python/jupytercad_lab/src/index.ts
Labels: enhancement

#360 Pin ajv
  packages/schema/package.json
Labels: maintenance

#362 Add constraints to form schema
  packages/schema/src/schema/box.json
  packages/schema/src/schema/chamfer.json
  packages/schema/src/schema/cone.json
  packages/schema/src/schema/cylinder.json
  packages/schema/src/schema/fillet.json
  packages/schema/src/schema/geomCircle.json
  packages/schema/src/schema/sphere.json
  packages/schema/src/schema/torus.json
Labels: enhancement

#365 Update github URL
  docs/source/conf.py
  package.json
  packages/base/package.json
  packages/occ-worker/package.json
  packages/opencascade/package.json
  packages/schema/package.json
  python/jupytercad_app/package.json
  python/jupytercad_app/src/app/plugins/mainmenu/menuWidget.ts
  python/jupytercad_core/package.json
  python/jupytercad_lab/package.json
Labels: maintenance

#366 Fix dry-run logic so that it does not run on the first load of the file
  packages/occ-worker/src/actions.ts
  packages/occ-worker/src/occapi/operatorCache.ts
  packages/occ-worker/src/occparser.ts
  packages/occ-worker/src/worker.ts
Labels: bug

#368 Fix extrusion form defaults
  packages/base/src/commands.ts
Labels: bug

#369 Improve deletion behavior
  packages/base/src/commands.ts
  packages/base/src/panelview/objecttree.tsx
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  ui-tests/tests/ui.spec.ts
Labels: enhancement

#371 Generate dropdowns for operands on operator properties
  packages/base/src/panelview/objectproperties.tsx
Labels: enhancement

#373 Workaround extruction non-solid issue
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
Labels: bug

#374 Unpin ajv
  packages/schema/package.json
  yarn.lock
Labels: maintenance

#375 Sync jupytercad_* version
  package.json
  python/jupytercad/pyproject.toml
  python/jupytercad/scripts/bump-version.py
Labels: maintenance
