Repository jupytercad/JupyterCAD, pull requests merged in 2024-12, with the labels that each got.

#579 Add suggestion panel
  .eslintrc.js
  .pre-commit-config.yaml
  package.json
  packages/base/package.json
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  packages/base/src/3dview/mainviewmodel.ts
  packages/base/src/commands.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/objecttree.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/suggestion/model.ts
  packages/base/src/suggestion/newForkDialog.tsx
  packages/base/src/suggestion/suggestionpanel.tsx
  packages/base/src/suggestion/view.tsx
  packages/base/src/tools.ts
  packages/base/src/types.ts
  packages/base/src/widget.ts
  packages/base/style/icon/chevron-right.svg
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytercad_app/package.json
  python/jupytercad_core/package.json
  python/jupytercad_lab/package.json
  python/jupytercad_lab/src/index.ts
  python/jupytercad_lab/style/base.css
  yarn.lock
Labels: enhancement

#622 Handle file renaming in panels
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/rightpanel.tsx
Labels: bug

#623 Introducing file versioning
  examples/test.jcad
  packages/schema/package.json
  packages/schema/schema.js
  packages/schema/src/doc.ts
  packages/schema/src/index.ts
  packages/schema/src/schema/jcad.json
  packages/schema/src/types.ts
  python/jupytercad_core/.gitignore
  python/jupytercad_core/jupytercad_core/handlers.py
  python/jupytercad_core/jupytercad_core/jcad_ydoc.py
  python/jupytercad_core/jupytercad_core/schema/__init__.py
  python/jupytercad_core/jupytercad_core/step_ydoc.py
  python/jupytercad_core/jupytercad_core/stl_ydoc.py
  python/jupytercad_core/pyproject.toml
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_core/src/stepplugin/model.ts
  python/jupytercad_core/src/stlplugin/model.ts
  python/jupytercad_lab/.gitignore
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
  python/jupytercad_lab/jupytercad_lab/notebook/objects/__init__.py
  python/jupytercad_lab/pyproject.toml
Labels: enhancement

#624 Copy & Paste objects
  packages/base/src/commands.ts
  packages/base/src/keybindings.json
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
Labels: enhancement

#628 Add labels to viewHelper
  packages/base/src/3dview/mainview.tsx
Labels: UX improvement, enhancement

#630 Improve primitive properties description
  packages/schema/src/schema/box.json
  packages/schema/src/schema/sphere.json
  packages/schema/src/schema/torus.json
Labels: enhancement

#631 More examples
  examples/pad.jcad
  examples/screwdriver.jcad
Labels: documentation

#632 Update README screenshot
  docs/source/assets/jupytercad-screenshot.png
Labels: documentation

#633 Update README - mention "collaborative" in the title
  python/jupytercad/README.md
Labels: documentation

#636 Missing pydantic dependency in jupytercad-core
  python/jupytercad_core/pyproject.toml
Labels: bug

#635 Add more examples
  examples/ArchDetail.jcad
  examples/Gear.jcad
Labels: documentation

#641 Improve file validation warning message
  packages/schema/src/model.ts
Labels: enhancement

#645 Add chess pawn example
  examples/pawn.jcad
Labels: documentation

#647 Improve pawn example
  examples/pawn.jcad
Labels: documentation

#649 Light logo for light mode and dark for dark
  docs/source/assets/jupytercad-light-ss.png
  python/jupytercad/README.md
Labels: documentation

#625 Replace @jupyterlab/rjsf with FormComponent from @jupyterlab/ui-components
  packages/base/package.json
  packages/base/src/panelview/customarrayfield.tsx
  packages/base/src/panelview/formbuilder.tsx
  python/jupytercad_lab/style/base.css
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/Exploded-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Console-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Modified-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/JCAD-Redo-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  yarn.lock
Labels: maintenance

#653 Fix placement for non-primitive shapes coming from freecad
  packages/occ-worker/src/actions.ts
  packages/occ-worker/src/occapi/any.ts
  packages/occ-worker/src/occapi/index.ts
  packages/occ-worker/src/occapi/loadObjectFile.ts
Labels: bug
