Repository jupytercad/JupyterCAD, pull requests merged in 2024-02, with the labels that each got.

#250 Fixing check-release workflow + Fix regression tests
  .github/workflows/build.yml
  .github/workflows/check-release.yml
Labels: maintenance

#252 Expose CadDocument from jupytercad
  examples/Notebook.ipynb
  python/jupytercad/jupytercad/__init__.py
Labels: bug

#254 Pin JupyterLab in publish release
  .github/workflows/publish-release.yml
Labels: bug

#255 Missing util
  python/jupytercad_app/webpack.config.js
  python/jupytercad_core/package.json
  yarn.lock
Labels: maintenance

#239 Jupyter Collaboration v2
  packages/base/package.json
  packages/schema/package.json
  python/jupytercad_app/package.json
  python/jupytercad_core/jupytercad_core/jcad_ydoc.py
  python/jupytercad_core/jupytercad_core/step_ydoc.py
  python/jupytercad_core/package.json
  python/jupytercad_core/pyproject.toml
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
  python/jupytercad_lab/jupytercad_lab/notebook/y_connector.py
  python/jupytercad_lab/package.json
  python/jupytercad_lab/pyproject.toml
  yarn.lock
Labels: maintenance

#251 Unpin jupyterlab in ui-tests
  .github/workflows/build.yml
  python/jupytercad/pyproject.toml
  python/jupytercad_app/pyproject.toml
  python/jupytercad_lab/pyproject.toml
  ui-tests/package.json
  ui-tests/tests/sketcher.spec.ts
  ui-tests/tests/tree.spec.ts-snapshots/Tree-Display-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts
  ui-tests/yarn.lock
Labels: maintenance

#238 Step file export to .jcad
  packages/base/src/commands.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytercad_core/jupyter-config/server-config/jupytercad_core.json
  python/jupytercad_core/jupytercad_core/__init__.py
  python/jupytercad_core/jupytercad_core/handlers.py
  python/jupytercad_core/pyproject.toml
  python/jupytercad_lab/src/index.ts
  scripts/dev-install.py
  ui-tests/tests/ui.spec.ts
Labels: enhancement

#329 Remove y-py
  python/jupytercad_core/jupytercad_core/jcad_ydoc.py
  python/jupytercad_core/pyproject.toml
  python/jupytercad_lab/pyproject.toml
Labels: maintenance
