Repository jupytercad/JupyterCAD, pull requests merged in 2024-03, with the labels that each got.

#246 Support for opening STL files
  .prettierignore
  package.json
  packages/occ-worker/src/occapi/loadObjectFile.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/any.json
  python/jupytercad_core/jupytercad_core/stl_ydoc.py
  python/jupytercad_core/pyproject.toml
  python/jupytercad_core/src/index.ts
  python/jupytercad_core/src/stlplugin/modelfactory.ts
  python/jupytercad_core/src/stlplugin/plugins.ts
  ui-tests/playwright.config.js
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-fan-stl-linux.png
Labels: enhancement

#331 Support JupyterLite
  .github/workflows/build.yml
  examples/test.jcad
  lite/environment.yml
  lite/jupyter-lite.json
  packages/base/src/mainview.tsx
  packages/schema/src/doc.ts
  packages/schema/src/index.ts
  packages/schema/src/model.ts
  packages/schema/src/types.ts
  python/jupytercad_core/jupytercad_core/jcad_ydoc.py
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_core/src/stepplugin/model.ts
  python/jupytercad_core/src/stepplugin/plugins.ts
  python/jupytercad_core/src/stlplugin/model.ts
  python/jupytercad_core/src/stlplugin/plugins.ts
Labels: enhancement

#332 Update JupyterLite config
  lite/jupyter_lite_config.json
Labels: enhancement

#334 Fix build shape from brep string
  packages/occ-worker/src/actions.ts
Labels: bug

#333 Implement clipping
  packages/base/src/commands.ts
  packages/base/src/mainview.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/base/src/types.ts
  packages/base/src/widget.tsx
  packages/base/style/icon/clipping.svg
  python/jupytercad_app/src/app/plugins/mainmenu/menuWidget.ts
Labels: enhancement

#336 Close warning before starting the UI test
  ui-tests/tests/notebook.spec.ts
  ui-tests/tests/sketcher.spec.ts
  ui-tests/tests/tree.spec.ts
  ui-tests/tests/ui.spec.ts
Labels: maintenance

#338 Update svg files
  packages/base/style/icon/axes.svg
  packages/base/style/icon/box.svg
  packages/base/style/icon/clipping.svg
  packages/base/style/icon/cone.svg
  packages/base/style/icon/cut.svg
  packages/base/style/icon/cylinder.svg
  packages/base/style/icon/extrusion.svg
  packages/base/style/icon/intersection.svg
  packages/base/style/icon/sphere.svg
  packages/base/style/icon/torus.svg
  packages/base/style/icon/union.svg
Labels: bug

#342 Add chamfer and fillet icons
  packages/base/style/icon/chamfer.svg
  packages/base/style/icon/fillet.svg
Labels: enhancement

#340 Edge operators
  .eslintrc.js
  packages/base/src/commands.ts
  packages/base/src/mainview.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/objecttree.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/base/style/icon/box.svg
  packages/base/style/icon/chamfer.svg
  packages/base/style/icon/cone.svg
  packages/base/style/icon/cylinder.svg
  packages/base/style/icon/fillet.svg
  packages/occ-worker/src/occapi/chamfer.ts
  packages/occ-worker/src/occapi/common.ts
  packages/occ-worker/src/occapi/fillet.ts
  packages/occ-worker/src/occapi/index.ts
  packages/occ-worker/src/occapi/operatorCache.ts
  packages/occ-worker/src/occparser.ts
  packages/occ-worker/src/types.ts
  packages/occ-worker/worker.webpack.config.js
  packages/opencascade/README.md
  packages/opencascade/build.yml
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/chamfer.json
  packages/schema/src/schema/fillet.json
  packages/schema/src/schema/jcad.json
  packages/schema/src/schema/placement.json
  packages/schema/src/types.ts
  python/jupytercad_app/src/main.ts
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
Labels: enhancement
