Repository jupytercad/JupyterCAD, pull requests merged in 2025-05, with the labels that each got.

#730 Update the switch mode label for the transform controls
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#731 Transform the normal console button into a toggle one
  packages/base/src/commands.ts
  packages/base/src/widget.ts
Labels: enhancement

#733 Use jupyterlab css variables for the selected suggestions
  packages/base/src/tools.ts
  packages/base/style/icon/visibility.svg
  python/jupytercad_lab/style/base.css
Labels: bug

#732 Apply the transform control on the parent when clicking on an edge
  packages/base/src/3dview/mainview.tsx
Labels: enhancement

#735 Properly handle lumino events
  packages/base/src/3dview/mainview.tsx
  packages/base/src/3dview/mainviewmodel.ts
  packages/base/src/3dview/mainviewwidget.tsx
  python/jupytercad_core/src/plugin.ts
Labels: bug

#737 Add 'New JupyterCAD file' option to context menu (jupytercad#634)
  python/jupytercad_core/src/jcadplugin/plugins.ts
Labels: enhancement

#740 Add multi-edge chamfer and fillet creation (jupytercad#646)
  packages/base/src/commands.ts
  packages/occ-worker/src/occapi/chamfer.ts
  packages/occ-worker/src/occapi/fillet.ts
  packages/schema/src/schema/chamfer.json
  packages/schema/src/schema/fillet.json
Labels: enhancement

#725 Introduce custom settings for JupyterCAD
  .github/workflows/build.yml
  packages/base/src/3dview/mainview.tsx
  packages/base/src/commands.ts
  packages/base/src/widget.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytercad_core/package.json
  python/jupytercad_core/schema/jupytercad-settings.json
  python/jupytercad_core/src/jcadplugin/modelfactory.ts
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_core/src/stepplugin/modelfactory.ts
  python/jupytercad_core/src/stepplugin/plugins.ts
  python/jupytercad_core/src/stlplugin/modelfactory.ts
  python/jupytercad_core/src/stlplugin/plugins.ts
  python/jupytercad_lab/src/notebookrenderer.ts
Labels: enhancement

#746 Update yarn lockfile resolving potential dependency conflicts
  packages/base/package.json
  python/jupytercad_app/package.json
  yarn.lock
Labels: maintenance
