Repository jupytercad/JupyterCAD, pull requests merged in 2025-02, with the labels that each got.

#676 Bump `actions/upload-artifact` to v4
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .readthedocs.yaml
Labels: maintenance

#679 Widget with toolbar and sidepanel in cell output
  examples/Notebook.ipynb
  packages/base/src/annotation/model.ts
  packages/base/src/commands.ts
  packages/base/src/formdialog.tsx
  packages/base/src/panelview/annotations.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/model.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/objecttree.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/types.ts
  packages/base/src/widget.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytercad_core/src/factory.ts
  python/jupytercad_core/src/jcadplugin/plugins.ts
  python/jupytercad_core/src/plugin.ts
  python/jupytercad_core/src/stepplugin/plugins.ts
  python/jupytercad_core/src/stlplugin/plugins.ts
  python/jupytercad_lab/src/notebookrenderer.ts
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
Labels: enhancement

#680 Enable Python API in the JupyterLite deployment
  .github/workflows/build.yml
  lite/environment.yml
  lite/jupyter-lite.json
  packages/base/src/widget.ts
  python/jupytercad/pyproject.toml
  python/jupytercad_app/package.json
  python/jupytercad_core/jupytercad_core/__init__.py
  python/jupytercad_core/pyproject.toml
  python/jupytercad_core/src/jcadplugin/modelfactory.ts
  python/jupytercad_core/src/stepplugin/modelfactory.ts
  python/jupytercad_core/src/stlplugin/modelfactory.ts
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
  python/jupytercad_lab/jupytercad_lab/notebook/utils.py
  python/jupytercad_lab/package.json
  python/jupytercad_lab/pyproject.toml
  python/jupytercad_lab/src/notebookrenderer.ts
  requirements-build.txt
  scripts/build_packages.py
  yarn.lock
Labels: enhancement

#681 Add `jupytercad_lite` metapackage
  .github/workflows/build.yml
  examples/Notebook.ipynb
  lite/environment.yml
  packages/base/src/widget.ts
  pyproject.toml
  python/jupytercad_lite/LICENSE
  python/jupytercad_lite/README.md
  python/jupytercad_lite/jupytercad/__init__.py
  python/jupytercad_lite/pyproject.toml
  python/jupytercad_lite/scripts/bump-version.py
  python/jupytercad_lite/setup.py
  scripts/build_packages.py
  scripts/dev-install.py
  ui-tests/tests/notebooks/Notebook.ipynb
Labels: enhancement

#682 Fix: Collaborative model
  packages/schema/src/model.ts
Labels: bug

#686 Handle string source coming from shared drive
  packages/schema/src/doc.ts
Labels: bug

#691 Fix bump script for jupytercad-lite
  python/jupytercad_lite/scripts/bump-version.py
Labels: bug

#692 Add setSource in stl & step plugin to fix lite deployment
  python/jupytercad_core/src/stepplugin/model.ts
  python/jupytercad_core/src/stlplugin/model.ts
Labels: bug

#693 Exclude `OCC` import from lite deployment
  .github/workflows/build.yml
  examples/Notebook.ipynb
  examples/occ.ipynb
Labels: documentation

#694 Install JupyterCAD metapackage in update snapshots workflow
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#696 Separate Bot for lite snapshot update
  .github/workflows/update_lite_galata_references.yaml
  ui-tests/package.json
Labels: maintenance

#698 Install jupyterlab to enable jlpm on update lite snaphots bot
  .github/workflows/update_lite_galata_references.yaml
Labels: bug
