Repository jupytercad/JupyterCAD, pull requests merged in 2025-04, with the labels that each got.

#703 Fix breaking change introduced in 3.1.0
  python/jupytercad_core/src/factory.ts
Labels: bug

#705 Pin docprovider
  python/jupytercad/pyproject.toml
  requirements-build.txt
Labels: bug

#710 Fix blank tab bug
  python/jupytercad_core/src/plugin.ts
Labels: bug

#711 Replace Deprecated `breptools_Write` with `breptools.Write`
  python/jupytercad_lab/jupytercad_lab/notebook/cad_document.py
Labels: bug

#713 Use svg icons only for the toolbar icons
  packages/base/src/commands.ts
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/base/style/icon/camera-solid.svg
  packages/base/style/icon/pencil-solid.svg
  packages/base/style/icon/terminal-toolbar.svg
Labels: enhancement

#717 Replace the formDialog by a toggle button for CameraSettings
  examples/jcad.ipynb
  packages/base/src/3dview/mainview.tsx
  packages/base/src/commands.ts
  packages/base/src/tools.ts
  packages/base/src/widget.ts
  packages/base/style/icon/camera-solid.svg
  packages/base/style/icon/video-solid.svg
Labels: enhancement

#719 Follow up of PR 717. Fix reassignment of cameraSettings
  packages/base/src/commands.ts
Labels: bug

#720 Use react state to show text message for clip plane
  packages/base/src/3dview/mainview.tsx
Labels: bug

#722 Replace the dialogform by a toggle button for the exploded view
  packages/base/src/3dview/mainview.tsx
  packages/base/src/commands.ts
  packages/base/src/widget.ts
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/Exploded-test-jcad-chromium-linux.png
Labels: enhancement

#724 Fix ArchDetail.jcad annotations model + check exploded view
  examples/ArchDetail.jcad
  packages/base/src/3dview/mainview.tsx
Labels: bug

#726 Replace the FormDialog by a toggle button for the axes helper
  packages/base/src/3dview/helpers.ts
  packages/base/src/3dview/mainview.tsx
  packages/base/src/commands.ts
  packages/base/src/types.ts
  packages/base/src/widget.ts
Labels: UX improvement, enhancement

#727 Follow up of PR 726. Fix the axes helper toggle button broken behavior
  packages/base/src/commands.ts
Labels: bug
